#!/bin/sh

ENCIMG=$1
MAPPER=$2
NAME="$3"

IDPREF=encryption:$ENCIMG

plain_unlock() {
    while true
    do
	PL=`systemd-ask-password --timeout=3600 --no-tty --id $IDPREF:1 "Encryption $NAME: Plain Text Password"`
	echo $PL | \
	    cryptsetup --allow-discards luksOpen $ENCIMG $MAPPER && \
	    echo Decrypted $ENCIMG && \
	    exit 0
	echo Failed to unlock $ENCIMG with provided recovery password
    done
}

hwcrypt_unlock() {
    while true
    do
	# without tmp variable, signing may fail on the first attempt with "no input available"
	PHW=`systemd-ask-password --timeout=3600 --no-tty --id $IDPREF:0 "Encryption $NAME: Password for Hardware Keystore"`
	echo $PHW | \
	    /usr/libexec/sailfish-device-encryption-community/hwcrypt-key $MAPPER | \
	    cryptsetup --allow-discards --key-file=- luksOpen $ENCIMG $MAPPER && \
	    echo Decrypted $ENCIMG && \
	    exit 0
	echo Failed to unlock $ENCIMG with provided hwcrypt password
    done
}

# request passwords - only one is sufficient to unlock

plain_unlock &

if [ -f /usr/libexec/droid-hybris/system/bin/hwcrypt ] && \
       [ -f /etc/sailfish-device-encryption-community/$MAPPER/hwcrypt/salt.conf ] ; then
    hwcrypt_unlock &
fi

# wait for one decryption to finish successfully
wait -n
jobs -p | xargs -r kill

# clean up remaining ask password processes
grep -l "Id=$IDPREF:" /run/systemd/ask-password/ask* | \
    xargs -r grep "PID=" | cut -d'=' -f2 | xargs -r kill

exit 0
