#!/bin/sh

ENCIMG=$1
MAPPER=$2

for i in 1 2 3 4 5; do
    echo Decrypt $ENCIMG: Attempt $i

    # without tmp variable, signing may fail on the first attempt with "no input available"
    P=`systemd-ask-password --no-tty --id encryption:$1:0 "Encryption $ENCIMG: Hardware Backed Password"`
    echo $P |
	/usr/libexec/sailfish-device-encryption-community/hwcrypt-key $MAPPER |
	cryptsetup --allow-discards --key-file=- luksOpen $ENCIMG $MAPPER && \
	    echo Decrypted $ENCIMG && \
	    exit 0

    systemd-ask-password --no-tty --id encryption:$1:1 "Encryption $ENCIMG: Recovery Password" |
	cryptsetup --allow-discards luksOpen $ENCIMG $MAPPER && \
	    echo Decrypted $ENCIMG && \
	    exit 0
done

exit 1
