#!/bin/sh

## Generate new signing key that can be used for LUKS container
## password derivation from user password. In addition, generate
## salt for argon. This script will generate key/salt only if they
## are missing. Existing key/salt will not trigger an error

HWCRYPT=/usr/libexec/droid-hybris/system/bin/hwcrypt
HWCRYPT_USER=encryption-hwcrypt

if [ "$#" -ne 2 ]; then
    echo "Usage: $0 keyname time-between-tries"
    echo
    echo "  keyname - unique name for this key"
    echo "  time-between-tries - minimal amount of time in seconds between two hardware key operations"
    exit 1
fi

MAPPER=$1
KEY=luks-$MAPPER
TIME=$2

# generate argon2 salt if needed
SALTFILE=/etc/sailfish-device-encryption-community/$MAPPER/hwcrypt/salt.conf
if [ ! -f $SALTFILE ]; then
    `dirname $0`/make-salt $SALTFILE || exit 1
fi

# exit if key is available already
systemd-run -q -P --uid=$HWCRYPT_USER \
	    $HWCRYPT haskey --name=$KEY \
    && exit 0

# generate key if missing
systemd-run -q -P --uid=$HWCRYPT_USER \
	    $HWCRYPT generate-signkg --name=$KEY --time-between-tries=$TIME \
    || exit 1
