#!/bin/bash

set -e

if [ "$#" -ne 1 ]; then
    echo "Usage: $0 saltfile"
    echo "  saltfile - Salt configuration file path."
    echo "             Example: /etc/sailfish-device-encryption-community/home_encrypted/hwcrypt/salt.conf"
    exit 1
fi

LENGTH=256
CONF=$1

mkdir -p `dirname $CONF`

SALT=`tr -dc A-Za-z0-9 </dev/urandom | head -c $LENGTH; echo ''`
echo "SALT=\"$SALT\"" > $CONF
